import image1 from './images/portrait.jpg';
import image2 from './images/portrait2.jpg';
import image3 from './images/portrait-big.jpg';
import image4 from './images/portrait4.jpg';
import image5 from './images/portrait-small1.jpg';
import image6 from './images/portrait1.jpg';
import image9 from './images/model3.jpg';
import image10 from './images/model4.jpg';
import image11 from './images/model5.jpg';
import image12 from './images/model6.jpg';
import image14 from './images/model13.jpg';
import image15 from './images/model12.jpg';
import image16 from './images/model14.jpg';
import image17 from './images/model11.jpg';
import image20 from './images/models13-small.jpg';
import image21 from './images/models8-small.jpg';
import image22 from './images/models7-small.jpg';
import image23 from './images/models27-small.jpg';
import image24 from './images/models14.jpg';
import image25 from './images/models18.jpg';
import image26 from './images/models10.jpg';
import image27 from './images/models15.jpg';
import image28 from './images/models3.jpg';
import image29 from './images/models24.jpg';
import image30 from './images/models25-small.jpg';
import image32 from './images/models20.jpg';

export const ImagesCarousel= [image1,image2,image3,image4,image5,image6];
export const ImagesModels=[image9,image10,image11,image12];
export const ImagesModels2=[image14,image15,image16,image17];
export const Images=[image20,image21,image22,image23,image24,image25,image26,image27,image28,image29,image30,image32];
